#!/bin/bash -e

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.8.0 --server https://sfranch.webdiscode.com --token j46rvt7dvpx64qqlbxlpf8f4br7kh846b2xxcz89v7hbswhsl6qjzb --etcd --controlplane --worker
