#!/bin/bash -e

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.8.0 --server https://cattle.webdiscode.com --token qq6schh8dr6vnptg2lfb58gb7mccn5lzbhddff2h4xsw6bkp62gcnj --worker
